### PR TITLE
Arm agents

### PR DESCRIPTION
**Pull request by 6543**
current error:
```
{"time":"2023-08-16T19:18:37Z","message":"Starting autoscaler with log-level=info"}
{"level":"info","agent":"pool-1-agent-TAUE","time":"2023-08-16T19:19:37Z","message":"deploying agent"}
{"level":"error","error":"hetznercloud: image has incompatible architecture (invalid_input)","time":"2023-08-16T19:19:37Z","message":"creating agents failed"}
{"level":"info","agent":"pool-1-agent-TAUE","reason":"not found on provider","time":"2023-08-16T19:20:37Z","message":"remove agent"}
```

### CODE REVIEW

**Comment by 6543** [comment]
depend on https://github.com/woodpecker-ci/autoscaler/pull/10

**Comment by 6543** [comment]
depend on https://github.com/woodpecker-ci/autoscaler/pull/12
and on https://github.com/woodpecker-ci/woodpecker/pull/2232

**Comment by anbraten** [comment]
We should implement https://github.com/woodpecker-ci/autoscaler/issues/72 to easily be able to have arm and amd64 agents be deployed as needed.

**Comment by anbraten** [comment]
replaced by #15

**Pull request closed without merging**
