### PR TITLE
community.docker.docker_container migrate pull from enum to bool

### PR DESCRIPTION
**Pull request by 6543**
"fatal: [ci_server]: FAILED! => {"changed": false, "msg": "argument 'pull' is of type <class 'str'> and we were unable to convert to bool:"

### CODE REVIEW

**Review by pat-s — COMMENTED** [review]
What caused this? `'always'` is a valid param value: https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-pull

**Comment by 6543** [comment]
hmm ... I did a deploy from my PC as the WP server was not responsive 

in the end a reboot of the server and #81 did bring it back ...

**Comment by 6543** [comment]
I locally checked out the main branch and did:
 - ``docker build -t ansible .`
 - `./ansible.sh ansible-playbook playbooks/run.yaml --tags woodpecker`

**Comment by 6543** [comment]
fixed by https://github.com/woodpecker-ci/infrastructure?tab=readme-ov-file#local-apply-via-nix witch is actually reproducable :D

**Pull request closed without merging**
